<?php
// Path to the MPD file (generated by FFmpeg)
$mpdFile = '/uploads/dash/LES_CHATONS_NINJAS_67e0eeb11551f_67e0eeb1159c8.mpd'; // Adjust the path to your MPD file
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Video Streaming</title>
    <script src="https://cdn.dashjs.org/latest/dash.all.min.js"></script> <!-- Load dash.js -->
</head>
<body>
    <h1>Watch Video</h1>

    <!-- Video element -->
    <video id="videoPlayer" controls></video>

    <script>
        // Initialize dash.js
        var video = document.getElementById('videoPlayer');
        var player = dashjs.MediaPlayer().create();
        player.initialize(video, '<?php echo $mpdFile; ?>', true);
    </script>
</body>
</html>
